server:
  port: 8080

fraud:
  service:
    url: ${FRAUD_SERVICE_URL:http://fraud-cve.banco-kokunas.svc.cluster.local}

spring:
  application:
    name: bankdemo
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:bankdemo}
    username: ${DB_USER:bankdemo}
    password: ${DB_PASSWORD:bankdemo}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

logging:
  level:
    com.kokunas.bankdemo: info
